# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libmagick++-dev
      - cargo

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = list("R/load.R" = c(32:33, 39:40, 46:47, 53:54)))'
